name: Push template to coder server

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  deploy_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Get short commit SHA # to use as template version name
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: "Install latest Coder"
        run: |
          curl -L https://coder.com/install.sh | sh
      - name: "Push template"
        run: |
          coder templates push <template-name> /--directory ./<template-directory> /
          --name ${{ steps.vars.outputs.sha_short }} /
          --yes
        env:
          # Consumed by Coder CLI
          CODER_URL: https://ghuntley.dev
          CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN }}
